alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['the-app-alert']
      group_wait: 30s
      group_interval: 5m
      receiver: 'default'
      repeat_interval: 12h
    receivers:
    - name: 'default'
      email_configs:
      - to: 'your-email@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'user'
        auth_password: 'password'